# Generated by Django 4.1.1 on 2022-10-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGym", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="entrenador",
            options={"verbose_name_plural": "Entrenadores"},
        ),
        migrations.AlterModelOptions(
            name="rutina",
            options={"verbose_name_plural": "Rutinas"},
        ),
    ]
